spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    username: postgres
    password: 1
    url: jdbc:postgresql://localhost:5432/labsBsuir
  jpa:
    show-sql: true
server:
  port: 8001